variable "aws_region" {
  description = "AWS region to deploy staging into."
  type        = string
  default     = "us-east-1"
}

variable "image_tag" {
  description = "Tag of the image in ECR to deploy (push this tag before running terraform apply)."
  type        = string
  default     = "latest"
}

# Non-secret RDS config - just identifiers, not credentials. The actual
# password is generated by modules/rds and never appears here.
variable "db_name" {
  description = "Name of the initial database created on the RDS instance."
  type        = string
  default     = "todos"
}

variable "master_username" {
  description = "Master username for the RDS instance."
  type        = string
  default     = "todo_app"
}

variable "multi_az" {
  description = "Whether RDS runs Multi-AZ. Roughly doubles RDS cost - false for staging (only prod needs the failover guarantee)."
  type        = bool
  default     = false
}

variable "environment" {
  description = "Environment name, used in tags."
  type        = string
  default     = "staging"

  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "environment must be one of: dev, staging, prod."
  }
}

variable "desired_count" {
  description = "Number of ECS tasks to run (initial value only if enable_autoscaling is true)."
  type        = number
  default     = 2
}

variable "enable_autoscaling" {
  description = "Whether to enable ECS service autoscaling (target tracking on CPU 70%). Enabled here to exercise the same scaling behavior as prod before it ships."
  type        = bool
  default     = true
}

variable "min_capacity" {
  description = "Minimum ECS task count when autoscaling is enabled."
  type        = number
  default     = 2
}

variable "max_capacity" {
  description = "Maximum ECS task count when autoscaling is enabled."
  type        = number
  default     = 6
}

variable "deletion_protection" {
  description = "Whether RDS rejects deletion until this is turned off. True for staging to mirror prod's guardrails."
  type        = bool
  default     = true
}

variable "backup_retention_period" {
  description = "RDS automated backup retention in days."
  type        = number
  default     = 3
}

variable "skip_final_snapshot" {
  description = "If true, terraform destroy deletes the instance without a final snapshot. False for staging - mirrors prod's safety, staging often holds data worth keeping."
  type        = bool
  default     = false
}
